version: '3.9'

services:

  db:
    build:
      context: mongodb/
    container_name: mongo_db
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    image: mongo_db:latest
    init: true
    ports:
      - "27017:27017"
    networks:
      - back_net
    volumes:
      - ./mongodb/data/db :/data/db

  mongo-express:
    build:
      context: mongo-express/
    container_name: mongo_express
    restart: always
    ports:
      - "8081:8081"
    networks:
      - back_net
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASS}
      ME_CONFIG_MONGODB_URL: ${DB_URL}
    image: mongo_express:latest
    init: True
    depends_on:
      - db

  webapp:
    build:
      context: .
    container_name: api
    env_file:
      - .env
    image: api:latest
    init: true
    networks:
      - back_net
    ports:
      - "8000:8000"
    depends_on:
      - db

networks:
  back_net:
    name: fastapi_app.local
    driver: bridge